### ISSUE TITLE
DuckieTV DEMO 0.90 trakt.tv access issue

### ISSUE THREAD

**Issue by garfield69** [DuckieTV/DuckieTV#1]
Cannot reach Trakt.TV  No-Access-Control-Allow-Origin.
![image](https://cloud.githubusercontent.com/assets/6933240/5895420/bbd9b99c-a583-11e4-9c59-4feab9b111d8.png)

**Comment by SchizoDuckie** [comment]
Requested permission from Justin @ Trakt. They'll have to manually allow this

**Comment by garfield69** [comment]
working now.
