### ISSUE TITLE
Favorites Missing, Backups Won’t Load, Can’t Add New Favorites

### ISSUE THREAD

**Issue by aphoughton** [DuckieTV/DuckieTV#6]
Favorites stopped appearing in the calendar a couple of months ago and nothing I have tried has resolved the issue. When I try to add new favorites or load a backup it shows a duck or ducks with the yellow square/spinning circle, but it never progresses beyond that. Please help.

**Comment by garfield69** [comment]
This GitHub repository is for the online DEMO version of DuckieTV accessed via http://duckietv.github.io/DuckieTV/, which is the wrong place to report problems with DuckieTV Stable or Nightly.

Please open a ticket via https://github.com/SchizoDuckie/DuckieTV/issues/new and we will try to help you there.
Thanks.
